---
- import_tasks: install.yml
- import_tasks: service.yml
- import_tasks: model.yml

- name: Allow Ollama port through UFW
  ufw:
    rule: allow
    port: "{{ ollama_port }}"
    proto: tcp
  become: true