- hosts: master
  become: true
  roles:
    - k3s-ufw
    - k3s-master

- hosts: nodes
  become: true
  roles:
    - k3s-ufw
    - k3s-agent

- hosts: all
  become: true
  tasks:
    - name: Restart k3s on master nodes after playbook apply
      systemd:
        name: k3s
        state: restarted
        daemon_reload: true
      when: "'master' in group_names"

    - name: Restart k3s-agent on worker nodes after playbook apply
      systemd:
        name: k3s-agent
        state: restarted
        daemon_reload: true
      when: "'nodes' in group_names"
