
[master]
kcontrol1 private_ip=192.168.178.100 smartctl_device=/dev/sda

[nodes]
ksai1
ksai2
kappsdata1
kmai1

[all:vars]
ansible_connection=ssh
ansible_user=dmytro
ansible_python_interpreter=/usr/bin/python3
